AWSTemplateFormatVersion: 2010-09-09

Description: Calls OpenShift templates to create resources

Parameters:
  VpcCidr:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-4]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-24.
    Default: 10.0.0.0/16
    Description: CIDR block for VPC.
    Type: String
  AvailabilityZoneCount:
    ConstraintDescription: "The number of availability zones. (Min: 1, Max: 3)"
    MinValue: 1
    MaxValue: 3
    Default: 1
    Description: "How many AZs to create VPC subnets for. (Min: 1, Max: 3)"
    Type: Number
  SubnetBits:
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/19-27.
    MinValue: 5
    MaxValue: 13
    Default: 12
    Description: "Size of each subnet to create within the availability zones. (Min: 5 = /27, Max: 13 = /19)"
    Type: Number

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "Network Configuration"
      Parameters:
      - VpcCidr
      - SubnetBits
    - Label:
        default: "Availability Zones"
      Parameters:
      - AvailabilityZoneCount
    ParameterLabels:
      AvailabilityZoneCount:
        default: "Availability Zone Count"
      VpcCidr:
        default: "VPC CIDR"
      SubnetBits:
        default: "Bits Per Subnet"



# TODO: Placeholder for Mappings
#Mappings:
#  ClassificationMap:
#      "Unclassified":
#        ClassificationText: "UNCLASSIFIED"
#        ClassificationScript: unclassified.js
#        ClassificationColor: "#5cb85c"
#      "Confidential":
#        ClassificationText: "CONFIDENTIAL"
#        ClassificationScript: confidential.js
#        ClassificationColor: "#286090"

# TODO: Placeholder for conditions
#Conditions:
#  CreateIAMResources: !Equals [ !Ref CreateIAMStack, true ]
#  CreateDNSResources: !Equals [ !Ref CreateElb, true ]
#  CreateAlarmResources: !Equals [ !Ref EnableAlarms, true ]
#  CreateStorageResources: !Not [ !Equals [!Ref NumberOfComputeStorages, 0]]
#  CreateStorageCloudwatch: !And
#  - !Condition CreateAlarmResources
#  - !Condition CreateStorageResources

Resources:

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://raw.githubusercontent.com/dmc5179/openshift4-aws-marketplace/main/01_vpc.yaml'
      Parameters:
        VpcCIDR: !Ref VpcCidr
        AvailabilityZoneCount: !Ref AvailabilityZoneCount
        SubnetBits: !Ref SubnetBits

# TODO: Incomplete
#  ClusterInfraStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: !Sub 'https://raw.githubusercontent.com/dmc5179/openshift4-aws-marketplace/main/02_cluster_infra.yaml'
#      Parameters:
#        VpcCIDR: !Ref VpcCidr
#        AvailabilityZoneCount: !Ref AvailabilityZoneCount
#        SubnetBits: !Ref SubnetBits

# TODO: Incomplete
#  ClusterSecurityStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: !Sub 'https://raw.githubusercontent.com/dmc5179/openshift4-aws-marketplace/main/03_cluster_security.yaml'
#      Parameters:
#        VpcCIDR: !Ref VpcCidr
#        AvailabilityZoneCount: !Ref AvailabilityZoneCount
#        SubnetBits: !Ref SubnetBits

# TODO: Incomplete
#  ClusterBootstrapStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: !Sub 'https://raw.githubusercontent.com/dmc5179/openshift4-aws-marketplace/main/04_cluster_bootstrap.yaml'
#      Parameters:
#        VpcCIDR: !Ref VpcCidr
#        AvailabilityZoneCount: !Ref AvailabilityZoneCount
#        SubnetBits: !Ref SubnetBits

# TODO: Incomplete
#  ClusterControlPlaneStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: !Sub 'https://raw.githubusercontent.com/dmc5179/openshift4-aws-marketplace/main/05_cluster_master_nodes.yaml'
#      Parameters:
#        VpcCIDR: !Ref VpcCidr
#        AvailabilityZoneCount: !Ref AvailabilityZoneCount
#        SubnetBits: !Ref SubnetBits

# TODO: Incomplete
#  ClusterApplicationPlaneStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: !Sub 'https://raw.githubusercontent.com/dmc5179/openshift4-aws-marketplace/main/06_cluster_worker_node.yaml'
#      Parameters:
#        VpcCIDR: !Ref VpcCidr
#        AvailabilityZoneCount: !Ref AvailabilityZoneCount
#        SubnetBits: !Ref SubnetBits
