AWSTemplateFormatVersion: 2010-09-09

Description: Calls OpenShift templates to create resources

Parameters:
  VpcCidr:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-4]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-24.
    Default: 10.0.0.0/16
    Description: CIDR block for VPC.
    Type: String
  AvailabilityZoneCount:
    ConstraintDescription: "The number of availability zones. (Min: 1, Max: 3)"
    MinValue: 1
    MaxValue: 3
    Default: 1
    Description: "How many AZs to create VPC subnets for. (Min: 1, Max: 3)"
    Type: Number
  SubnetBits:
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/19-27.
    MinValue: 5
    MaxValue: 13
    Default: 12
    Description: "Size of each subnet to create within the availability zones. (Min: 5 = /27, Max: 13 = /19)"
    Type: Number

  ClusterName:
    AllowedPattern: ^([a-zA-Z][a-zA-Z0-9\-]{0,26})$
    MaxLength: 27
    MinLength: 1
    ConstraintDescription: Cluster name must be alphanumeric, start with a letter, and have a maximum of 27 characters.
    Description: A short, representative cluster name to use for host names and other identifying names.
    Type: String
  InfrastructureName:
    AllowedPattern: ^([a-zA-Z][a-zA-Z0-9\-]{0,26})$
    MaxLength: 27
    MinLength: 1
    ConstraintDescription: Infrastructure name must be alphanumeric, start with a letter, and have a maximum of 27 characters.
    Description: A short, unique cluster ID used to tag cloud resources and identify items owned or used by the cluster.
    Type: String
  HostedZoneId:
    Description: The Route53 public zone ID to register the targets with, such as Z21IXYZABCZ2A4.
    Type: String
  HostedZoneName:
    Description: The Route53 zone to register the targets with, such as example.com. Omit the trailing period.
    Type: String
    Default: "example.com"
#  PublicSubnets:
#    Description: The internet-facing subnets.
#    Type: List<AWS::EC2::Subnet::Id>
#  PrivateSubnets:
#    Description: The internal subnets.
#    Type: List<AWS::EC2::Subnet::Id>
#  VpcId:
#    Description: The VPC-scoped resources will belong to this VPC.
#    Type: AWS::EC2::VPC::Id





##############################################

# TODO: Placeholder for Mappings
Mappings:
  RHELAmi:
    us-east-1:
      "HVM64": ""
    us-east-2:
      "HVM64": "ami-03d64741867e7bb94"
    us-west-1:
      "HVM64": ""
    eu-west-1:
      "HVM64": ""
  RHCOSAmi:
    us-east-1:
      "HVM64": ""
    us-east-2:
      "HVM64": "ami-01424161073016df8"
    us-west-1:
      "HVM64": ""
    eu-west-1:
      "HVM64": ""

# TODO: Placeholder for conditions
#Conditions:
#  CreateIAMResources: !Equals [ !Ref CreateIAMStack, true ]
#  CreateDNSResources: !Equals [ !Ref CreateElb, true ]
#  CreateAlarmResources: !Equals [ !Ref EnableAlarms, true ]
#  CreateStorageResources: !Not [ !Equals [!Ref NumberOfComputeStorages, 0]]
#  CreateStorageCloudwatch: !And
#  - !Condition CreateAlarmResources
#  - !Condition CreateStorageResources

Resources:

# TODO: Needs testing
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://raw.githubusercontent.com/dmc5179/openshift4-aws-marketplace/main/01_vpc.yaml'
      Parameters:
        VpcCIDR: !Ref VpcCidr
        AvailabilityZoneCount: !Ref AvailabilityZoneCount
        SubnetBits: !Ref SubnetBits

# TODO: Needs testing
  ClusterInfraStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://raw.githubusercontent.com/dmc5179/openshift4-aws-marketplace/main/02_cluster_infra.yaml'
      Parameters:
        ClusterName: !Ref ClusterName
        InfrastructureName: !Ref InfrastructureName
        HostedZoneId: !Ref HostedZoneId
        HostedZoneName: !Ref HostedZoneName
        PublicSubnets: !Sub '${AWS::StackName}-PublicSubnetIds'
        PrivateSubnets: !Sub '${AWS::StackName}-PrivateSubnetIds'
        VpcId: !Sub '${AWS::StackName}-VPCID'

# TODO: Needs testing
  ClusterSecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://raw.githubusercontent.com/dmc5179/openshift4-aws-marketplace/main/03_cluster_security.yaml'
      Parameters:
        InfrastructureName: !Ref InfrastructureName
        VpcCidr: !Ref VpcCidr
        VpcId: !Sub '${AWS::StackName}-VPCID'
        PrivateSubnets: !Sub '${AWS::StackName}-PrivateSubnetIds'

# TODO: Add stack for the helper node
  HelperNodeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://raw.githubusercontent.com/dmc5179/openshift4-aws-marketplace/main/03_heler_node.yaml'
      Parameters:
        ImageId: !FindInMap [RHELAmi, !Ref "AWS::Region", HVM64]

# TODO: Incomplete
#  ClusterBootstrapStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: !Sub 'https://raw.githubusercontent.com/dmc5179/openshift4-aws-marketplace/main/04_cluster_bootstrap.yaml'
#      Parameters:

# TODO: Incomplete
#  ClusterControlPlaneStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: !Sub 'https://raw.githubusercontent.com/dmc5179/openshift4-aws-marketplace/main/05_cluster_master_nodes.yaml'
#      Parameters:

# TODO: Incomplete
#  ClusterApplicationPlaneStack:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: !Sub 'https://raw.githubusercontent.com/dmc5179/openshift4-aws-marketplace/main/06_cluster_worker_node.yaml'
#      Parameters:
